const $=s=>document.querySelector(s);
const input=$("#textInput"),targetInput=$("#targetCount"),message=$("#message");
const URL_RE=/(?:https?:\/\/|www\.)[^\s<>"'「」『』]+/gi;
const JAPANESE_RE=/[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uff66-\uff9f]/u;
const ALPHA_RE=/[A-Za-zＡ-Ｚａ-ｚ]/u,NUMBER_RE=/[0-9０-９]/u,SPACE_RE=/\s/u;
const PUNCTUATION_MAP={",":"、",".":"。","!":"！","?":"？",":":"：",";":"；"};
const SNS_LIMITS={x:280,xjp:140,xlong:25000,bluesky:300,instagram:2200,threads:500};
let undoStack=[],redoStack=[],lastCommitted=input.value,suppressHistory=false,typingTimer;
function chars(t){return Array.from(t)}
function countEmoji(t){if(!t)return 0;if(typeof Intl!=="undefined"&&Intl.Segmenter){const s=new Intl.Segmenter(undefined,{granularity:"grapheme"});let n=0;for(const{segment}of s.segment(t))if(/\p{Extended_Pictographic}/u.test(segment))n++;return n}return(t.match(/\p{Extended_Pictographic}/gu)||[]).length}
function getStats(text){const list=chars(text),withoutUrls=text.replace(URL_RE,""),urlExcluded=chars(withoutUrls);let japanese=0,alpha=0,number=0,spaces=0,lineBreaks=0,symbols=0;for(const c of list){if(c==="\n"||c==="\r")lineBreaks++;if(SPACE_RE.test(c))spaces++;if(JAPANESE_RE.test(c))japanese++;else if(ALPHA_RE.test(c))alpha++;else if(NUMBER_RE.test(c))number++;else if(!SPACE_RE.test(c)&&c!=="\n"&&c!=="\r")symbols++}return{characters:list.length,urlExcluded:urlExcluded.length,excludedWhitespace:chars(text.replace(/[\s]/gu,"")).length,lineBreaks,spaces,japanese,alpha,number,symbols,emoji:countEmoji(text),lines:text?text.split(/\r?\n/).length:1}}
function render(){const text=input.value,stats=getStats(text),target=Math.max(0,Number(targetInput.value)||0);$("#charCount").textContent=stats.characters.toLocaleString();$("#charCountIncluded").textContent=stats.characters.toLocaleString();$("#charCountExcluded").textContent=stats.excludedWhitespace.toLocaleString();$("#heroCount").textContent=stats.characters.toLocaleString();$("#urlExcludedCount").textContent=stats.urlExcluded.toLocaleString();$("#lineBreakCount").textContent=stats.lineBreaks.toLocaleString();$("#spaceCount").textContent=stats.spaces.toLocaleString();$("#japaneseCount").textContent=stats.japanese.toLocaleString();$("#alphaCount").textContent=stats.alpha.toLocaleString();$("#numberCount").textContent=stats.number.toLocaleString();$("#symbolCount").textContent=stats.symbols.toLocaleString();$("#emojiCount").textContent=stats.emoji.toLocaleString();$("#lineInfo").textContent=stats.lines.toLocaleString()+"行";$("#wordInfo").textContent=stats.characters.toLocaleString()+"文字";const percent=target>0?Math.min(100,stats.characters/target*100):0;$("#progressBar").style.width=percent+"%";$("#progressPercent").textContent=Math.round(percent)+"%";$("#progressText").textContent=target===0?"目標文字数を設定してください":stats.characters<target?"あと "+(target-stats.characters).toLocaleString()+" 文字":stats.characters===target?"ぴったり！":target.toLocaleString()+"文字を "+(stats.characters-target).toLocaleString()+"文字超過";updateHistoryButtons()}
function showMessage(t){message.textContent=t;clearTimeout(showMessage.timer);showMessage.timer=setTimeout(()=>message.textContent="",2400)}
function pushUndo(value){if(value===input.value)return;undoStack.push(value);if(undoStack.length>100)undoStack.shift();redoStack=[];lastCommitted=input.value;updateHistoryButtons()}
function setText(t,n){if(t===input.value){if(n)showMessage(n);return}pushUndo(input.value);suppressHistory=true;input.value=t;suppressHistory=false;lastCommitted=t;render();if(n)showMessage(n);input.focus()}
function updateHistoryButtons(){$("#undoButton").disabled=undoStack.length===0;$("#redoButton").disabled=redoStack.length===0}
function undo(){if(!undoStack.length)return;redoStack.push(input.value);input.value=undoStack.pop();lastCommitted=input.value;render();showMessage("元に戻しました")}
function redo(){if(!redoStack.length)return;undoStack.push(input.value);input.value=redoStack.pop();lastCommitted=input.value;render();showMessage("やり直しました")}
function normalizeSpaces(t){return t.replace(/[ \t\u3000]+/g," ").replace(/^[ ]+|[ ]+$/gm,"")}
function trimLines(t){return t.replace(/^[ \t\u3000]+|[ \t\u3000]+$/gm,"")}
function normalizeLineBreaks(t){return t.replace(/\r\n?/g,"\n").replace(/\n{3,}/g,"\n\n").trim()}
function normalizeWidth(t){return t.replace(/[！-～]/g,c=>{const a=String.fromCharCode(c.charCodeAt(0)-0xfee0);return /[A-Za-z0-9!"#$%&'()*+,\-./:;<=>?@[\]^_{}|~]/.test(a)?a:c}).replace(/　/g," ")}
function protectUrls(text,fn){const urls=[];const masked=text.replace(URL_RE,u=>{const key="__TP_URL_"+urls.length+"__";urls.push(u);return key});return fn(masked).replace(/__TP_URL_(\d+)__/g,(_,i)=>urls[Number(i)])}
function normalizePunctuation(t){return protectUrls(t,s=>s.replace(/[,.!?:;]/g,c=>PUNCTUATION_MAP[c]||c))}
function normalizeQuotes(t){let open=true;return t.replace(/[“”]/g,c=>c==="“"?"「":"」").replace(/"/g,()=>{const q=open?"「":"」";open=!open;return q}).replace(/(?<![\p{L}\p{N}])'([^']+)'/gu,"「$1」")}
function formatBullets(t){return t.replace(/^[ \t]*[-*+・]+[ \t]*/gm,"・").replace(/^[ \t]*[•●○][ \t]*/gm,"・")}
function addBullets(t){return t.split(/\r?\n/).map(line=>{if(!line.trim())return line;if(/^[ \t]*(?:[-*+・•●○])\s*/.test(line))return line;return "・ "+line.replace(/^[ \t]+/,"")}).join("\n")}
function applyLineMode(t,mode){if(mode==="join")return t.replace(/\r\n?/g,"\n").replace(/\n/g,"");if(mode==="single")return t.replace(/\r\n?/g,"\n").replace(/\n{2,}/g,"\n");if(mode==="blank")return t.replace(/\r\n?/g,"\n").split("\n").filter(line=>line.trim()!=="").join("\n");if(mode==="double")return t.replace(/\r\n?/g,"\n").replace(/\n{3,}/g,"\n\n");if(mode==="char")return Array.from(t.replace(/\r\n?/g,"\n").replace(/\n/g,"")).join("\n");return t}
function hiraganaToKatakana(t){return t.replace(/[\u3041-\u3096]/g,c=>String.fromCharCode(c.charCodeAt(0)+0x60))}
function katakanaToHiragana(t){return t.replace(/[\u30a1-\u30f6]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60))}
const HALF_KATA_MAP={"。":"｡","「":"｢","」":"｣","、":"､","・":"･","ー":"ｰ","ァ":"ｧ","ア":"ｱ","ィ":"ｨ","イ":"ｲ","ゥ":"ｩ","ウ":"ｳ","ェ":"ｪ","エ":"ｴ","ォ":"ｫ","オ":"ｵ","カ":"ｶ","ガ":"ｶﾞ","キ":"ｷ","ギ":"ｷﾞ","ク":"ｸ","グ":"ｸﾞ","ケ":"ｹ","ゲ":"ｹﾞ","コ":"ｺ","ゴ":"ｺﾞ","サ":"ｻ","ザ":"ｻﾞ","シ":"ｼ","ジ":"ｼﾞ","ス":"ｽ","ズ":"ｽﾞ","セ":"ｾ","ゼ":"ｾﾞ","ソ":"ｿ","ゾ":"ｿﾞ","タ":"ﾀ","ダ":"ﾀﾞ","チ":"ﾁ","ヂ":"ﾁﾞ","ッ":"ｯ","ツ":"ﾂ","ヅ":"ﾂﾞ","テ":"ﾃ","デ":"ﾃﾞ","ト":"ﾄ","ド":"ﾄﾞ","ナ":"ﾅ","ニ":"ﾆ","ヌ":"ﾇ","ネ":"ﾈ","ノ":"ﾉ","ハ":"ﾊ","バ":"ﾊﾞ","パ":"ﾊﾟ","ヒ":"ﾋ","ビ":"ﾋﾞ","ピ":"ﾋﾟ","フ":"ﾌ","ブ":"ﾌﾞ","プ":"ﾌﾟ","ヘ":"ﾍ","ベ":"ﾍﾞ","ペ":"ﾍﾟ","ホ":"ﾎ","ボ":"ﾎﾞ","ポ":"ﾎﾟ","マ":"ﾏ","ミ":"ﾐ","ム":"ﾑ","メ":"ﾒ","モ":"ﾓ","ャ":"ｬ","ヤ":"ﾔ","ュ":"ｭ","ユ":"ﾕ","ョ":"ｮ","ヨ":"ﾖ","ラ":"ﾗ","リ":"ﾘ","ル":"ﾙ","レ":"ﾚ","ロ":"ﾛ","ヮ":"ﾜ","ワ":"ﾜ","ヰ":"ｲ","ヱ":"ｴ","ヲ":"ｦ","ン":"ﾝ","ヴ":"ｳﾞ","ヵ":"ｶ","ヶ":"ｹ","ヷ":"ﾜﾞ","ヸ":"ｲﾞ","ヹ":"ｴﾞ","ヺ":"ｦﾞ","ヿ":"ｺﾄ"};
function toHalfKatakana(t){return t.replace(/[。「」、・ーァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロヮワヰヱヲンヴヵヶヷヸヹヺヿ]/g,c=>HALF_KATA_MAP[c]||c)}
function toFullKatakana(t){return t.normalize("NFKC")}
function symbolHalf(t){return t.replace(/[！-～]/g,c=>{const a=String.fromCharCode(c.charCodeAt(0)-0xfee0);return /[A-Za-z0-9]/.test(a)?c:a})}
function symbolFull(t){return t.replace(/[!"#$%&'()*+,\-./:;<=>?@[\]^_{}|~]/g,c=>String.fromCharCode(c.charCodeAt(0)+0xfee0))}
function convertText(t,type){switch(type){case"hiragana":return katakanaToHiragana(t);case"katakana":return hiraganaToKatakana(t);case"halfKatakana":return toHalfKatakana(t);case"fullKatakana":return toFullKatakana(t);case"lower":return t.toLowerCase();case"upper":return t.toUpperCase();case"numberHalf":return t.replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xfee0));case"numberFull":return t.replace(/[0-9]/g,c=>String.fromCharCode(c.charCodeAt(0)+0xfee0));case"symbolHalf":return symbolHalf(t);case"symbolFull":return symbolFull(t);default:return t}}
const actions={spaces:{label:"余分な空白を整理しました",fn:normalizeSpaces},linebreaks:{label:"連続した改行を整理しました",fn:normalizeLineBreaks},width:{label:"全角・半角を整理しました",fn:normalizeWidth},punctuation:{label:"句読点を統一しました",fn:normalizePunctuation},quotes:{label:"括弧・引用符を整理しました",fn:normalizeQuotes},trimLines:{label:"すべての行の前後をトリミングしました",fn:trimLines}};
document.querySelectorAll(".tool-button").forEach(b=>b.addEventListener("click",()=>{const a=actions[b.dataset.action];if(a)setText(a.fn(input.value),a.label)}));
input.addEventListener("input",()=>{if(suppressHistory){render();return}render();clearTimeout(typingTimer);typingTimer=setTimeout(()=>{if(input.value!==lastCommitted){undoStack.push(lastCommitted);if(undoStack.length>100)undoStack.shift();redoStack=[];lastCommitted=input.value;updateHistoryButtons()}},500)});
targetInput.addEventListener("input",render);
$("#snsMode").addEventListener("change",()=>{const v=$("#snsMode").value;if(v){targetInput.value=SNS_LIMITS[v];render();showMessage("SNSモードの目標文字数を設定しました")}});
$("#undoButton").addEventListener("click",undo);$("#redoButton").addEventListener("click",redo);
$("#applyLineMode").addEventListener("click",()=>{const mode=document.querySelector('input[name="lineMode"]:checked').value;setText(applyLineMode(input.value,mode),"改行設定を適用しました")});
$("#applyConversion").addEventListener("click",()=>setText(convertText(input.value,$("#conversionType").value),"変換しました"));
$("#replaceButton").addEventListener("click",()=>{const from=$("#replaceFrom").value,to=$("#replaceTo").value,regex=$("#regexMode").checked;if(!from)return showMessage("検索する文字列を入力してください");try{const pattern=regex?new RegExp(from,"gu"):new RegExp(from.replace(/[.*+?^$()|[\]\\]/g,"\\$&"),"gu");setText(input.value.replace(pattern,to),regex?"正規表現で置換しました":"文字列を置換しました")}catch(e){showMessage("正規表現が正しくありません")}});
$("#copyButton").addEventListener("click",async()=>{if(!input.value)return showMessage("コピーする文章がありません");try{await navigator.clipboard.writeText(input.value);showMessage("文章をクリップボードにコピーしました")}catch{input.select();document.execCommand("copy");input.setSelectionRange(input.value.length,input.value.length);showMessage("文章をコピーしました")}});
$("#extractUrls").addEventListener("click",()=>{const urls=input.value.match(URL_RE)||[];if(!urls.length)return showMessage("URLは見つかりませんでした");setText(urls.join("\n"),urls.length+"件のURLを抽出しました")});
$("#formatBullets").addEventListener("click",()=>setText(formatBullets(input.value),"箇条書きを整えました"));
$("#addBullets").addEventListener("click",()=>setText(addBullets(input.value),"各行の先頭に・を追加しました"));
$("#clearButton").addEventListener("click",()=>setText("","入力内容をクリアしました"));
$("#sampleButton").addEventListener("click",()=>setText("Text Polishのサンプル文章です。  余分な空白や\n\n\n連続した改行を整理して、文字数も確認できます。\nhttps://example.com/sample","サンプル文章を入力しました"));
$("#fileInput").addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setText(String(reader.result||""),file.name+"を読み込みました");reader.readAsText(file,"UTF-8")});
$("#saveButton").addEventListener("click",()=>{if(!input.value)return showMessage("保存する文章がありません");const blob=new Blob([input.value],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="text-polish.txt";a.click();URL.revokeObjectURL(url);showMessage("TXTファイルを保存しました")});
render();